### ISSUE TITLE
`randomstuff.AuthError` not raising when providing wrong API key.

### ISSUE THREAD

**Issue by nerdguyahmad** [nerdguyahmad/randomstuff.py#1]
## Description
When you provide the wrong API key in `randomstuff.Client` or `randomstuff.AsyncClient`, It is supposed to raise `randomstuff.errors.AuthError` on next API call but it doesn't. Instead, It simply returns "unauthorized".

## Steps to Reproduce
1. Make an instance of `randomstuff.Client` or `randomstuff.AsyncClient` with wrong or invalid API key in `key` parameter.
2. Make an API call.

## Expected results
It should raise `randomstuff.errors.AuthError`. 

## Obtained results
It returns `unauthorized` message as a string.

## Possible fixes
The error code in if statement on line 39 in client.py probably has wrong status code.

**Comment by nerdguyahmad** [comment]
**UPDATE:** This is because Random Stuff API is returning 200 status code regardless of errors. 
https://github.com/pgamerxdev/projects/issues/18

**Comment by pgamerxdev** [comment]
It Looks like I won't be able to fix it since ExpressJS Doesn't provide that facility in the version I am using.
I will upgrade the version once my exams are finished i.e in about a week
