### ISSUE TITLE
AttributeError on rate limits

### ISSUE THREAD

**Issue by nerdguyahmad** [nerdguyahmad/randomstuff.py#13]
API returns a list with first element as message which causes the library to raise AttributeError:
```py
'str' object has no attribute get
```

**Comment by nerdguyahmad** [comment]
> Can you specify the endpoint
> @nerdguyahmad

My bad, @Creepy-Creeper3625 , It's `v4/ai` endpoint.

**Comment by Creepy-Creeper3625** [comment]
Will look into his ASAP @nerdguyahmad

**Comment by Creepy-Creeper3625** [comment]
@nerdguyahmad 
Can I get the full trace back?

**Comment by nerdguyahmad** [comment]
> @nerdguyahmad 
> Can I get the full trace back?

Actually it's in `objects.BaseObject` class, on:
```py
self.message = data[0].get("message")
```
line. I got to know about this error in Discord server. I don't have the traceback and I'm kinda busy so I can't reproduce yet since I'm busy. Here's a summary of things I know:

This is what normal (AI) returned data looks like:
```json
[{
  "message": "ai response",
  },
  {
  "response_time": "Normal"
  }
]
```
And this is what the response looks like when there's a ratelimit:
```json
["Ratelimit message"]
```
So, The problem is pretty clear and self explanatory. `data[0]` (unlike normal response) is a string. 
 

I hope you can fix this. I'm busy right now woth other projects. :)

**Comment by nerdguyahmad** [comment]
First approach towards rate limit handling. Though I'd love to see some improvements to API itself.

**Comment by Creepy-Creeper3625** [comment]
@nerdguyahmad 
Will fix and push today.

**Comment by nerdguyahmad** [comment]
#15 Fixed this.
