### ISSUE TITLE
[TODO] Warnings not coloured properly 

### ISSUE THREAD

**Issue by nerdguyahmad** [nerdguyahmad/randomstuff.py#14]
The warnings that are supposed to be orange in terminal are only orange on Linux based systems. On windows, It simply prints the raw code. 

## Possible Workaround
Use `colorama.init()` on windows.

**Comment by Creepy-Creeper3625** [comment]
There are no possible workaround for this issue other than using colorama. Therefore will make changes to the code.
@nerdguyahmad

**Comment by Creepy-Creeper3625** [comment]
Close these @nerdguyahmad

**Comment by nerdguyahmad** [comment]
#15 Fixed this.
