### ISSUE TITLE
Joke not working

### ISSUE THREAD

**Issue by pgamerxdev** [nerdguyahmad/randomstuff.py#3]
AI works, image works
But joke doesn't

**Comment by nerdguyahmad** [comment]
> AI works, image works
> But joke doesn't

What's the error?

**Comment by nerdguyahmad** [comment]
`get_joke()` is supposed to return the `randomstuff.Joke` object for easier usage you can use attributes with it to get the joke and other details. See https://github.com/nerdguyahmad/randomstuff.py/blob/main/examples/jokes.py

**Comment by nerdguyahmad** [comment]
Fixed https://github.com/nerdguyahmad/randomstuff.py/commit/2d7af89003b4a3b84c761ddba100630404a48a23
